replicaCount: 1

image:
  repository: browneyed.kr.ncr.ntruss.com/studyon
  pullPolicy: Always
  tag: ""

imagePullSecrets:
#   - name: regcred
nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 80

dbService:
  type: ClusterIP
  port: 5432

django:
  replicaCount: 1
  containerPort: 8000
  configMap:
    RUN_MODE: "staging"
  secret:
    DJANGO_SECRET_KEY: enter_your_secret_key

db:
  secret:
    POSTGRES_DB: enter_your_db_name
    POSTGRES_USER: enter_your_db_user
    POSTGRES_PASSWORD: enter_your_db_password
    POSTGRES_PORT: "5432"
