apiVersion: v1
kind: Secret
metadata:
  name: {{ include "studyon.db.fullname" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- range $key, $val := .Values.db.secret }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}