apiVersion: v1
kind: Service
metadata:
  name: {{ include "studyon.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "studyon.labels" . | nindent 4 }}
  annotations:
    service.beta.kubernetes.io/ncloud-load-balancer-tls-ports: "443"
    service.beta.kubernetes.io/ncloud-load-balancer-ssl-certificate-no: "20673"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 443
      targetPort: http
      protocol: TCP
      name: https
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "studyon.selectorLabels" . | nindent 4 }}