apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "studyon.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  DB_HOST: {{ include "studyon.db.fullname" . }}
  {{- range $key, $value := .Values.django.configMap }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}