apiVersion: v1
kind: Secret
metadata:
  name: {{ include "studyon.fullname" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  DJANGO_SECRET_KEY: {{ .Values.django.secret.DJANGO_SECRET_KEY | b64enc | quote }}