apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "studyon.redis.fullname" . }}
  namespace: {{ .Release.Namespace }}
data: 
  redis_conf: {{- .Values.redis.configMap.redis_conf | toYaml | indent 2 }}